spring.application.name=AppBasketImanolVictor

# Base de datos - Usar el nombre del servicio de docker, NO localhost
spring.datasource.url=jdbc:postgresql://postgres:5432/fabaragon_db
spring.datasource.username=admin
spring.datasource.password=Admin17#
spring.datasource.driver-class-name=org.postgresql.Driver
server.address=0.0.0.0
server.port=8080
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=tu_clave_secreta_muy_segura_para_desarrollo_2024
jwt.expiration=86400000

# Email (para verificacion)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=imanollapiozondo@gmail.com
spring.mail.password=oxrscakwredlmuxn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Clave de administrador para registro
admin.secret.key=ClaveAdminSuperSegura!2026
