spring.application.name=AppBasketImanolVictor

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/fabaragon_db
spring.datasource.username=admin
spring.datasource.password=Admin17#
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#JWT
jwt.secret=MiClaveSuperSeguraDe32CaracteresOFrasesLargas
jwt.expiration=86400000

# Errores
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never


# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=imanollapizondocarreras@gmail.com
spring.mail.password=ItacaIma17
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true